### ISSUE TITLE
use seqBlockApply in getGenotype* methods

### ISSUE THREAD

**Issue by smgogarten** [smgogarten/SeqVarTools#2]
See if `seqApply` can be replaced with `seqBlockApply` to speed up `getGenotype` and `getGenotypeAlleles`.

**Comment by thierrygosselin** [comment]
Hi Stephanie,
In `SeqVarTools::getGenotypeAlleles` I see that we can pass further arguments in 
the dots-dots-dots for `seqBlockApply`. Is this developed (anything I could test?) 
or under development ?

Thanks
Thierry

**Comment by smgogarten** [comment]
Currently `seqBlockApply` (and the `...` argument) is used only in `refDosage` and `altDosage`, but not in any of the other methods.

**Comment by smgogarten** [comment]
I tried this, but the implementation with `seqBlockApply` ended up being slower than the original. Sorry!

**Comment by thierrygosselin** [comment]
No worries, at least we know!
