### ISSUE TITLE
Possible bug when running applyMethod when specifying both sample and variant filters to apply method to at once. 

### ISSUE THREAD

**Issue by gtollefson** [smgogarten/SeqVarTools#7]
Hi @smgogarten , 

I observe different output for the same sample and same variant when running applyMethod() using a custom function (pasted at the bottom of this report) when either specifying a list of samples and variants to run applyMethod() on versus when specifying only one variant to run it on. The possible bug manifests when specifying both a list of variants and samples to run the function on at once. I've outlined my three tests illustrating this unexpected behavior below:

I'd like to know whether supplying both sample and variant parameters to applyMethod at once is supported. I only see examples using one or the other in the vignette though the function description suggests both may be applied at once. If it is supported, could you help me to troubleshoot this discrepency?

# Test 1: Run on list of variants and samples (This is bug reproduction)

**Command:**
> input_data_sample_ids <- seqGetData(gdsobj,"sample.id")
> coding_wsaf_table <- applyMethod(gdsobj,calc_AF_per_nucleotide,sample=input_data_sample_ids,variant=filtered_variant_ids)

**Output:** (Note: only listing one output since printed message is too long to find others and this is sufficient to show problem in the example):

> [995] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 0  | Genotype: 0  | Read Depth: 18  | WSAF: NaN"       

                                    

# Test 2: Run on one sample and one variant (Appears to run as expected)

**Command:**

> test_var_id <- "PF3D7_0319700-p.Ile2221Phe"
> test_sample_id <-"KB-00-39" 
> coding_wsaf_table <- applyMethod(gdsobj,calc_AF_per_nucleotide,sample=test_sample_id,variant=all_variant_ids[which(gene_aa_change == test_var_id)])

**Output:**

>  of selected samples: 1
> of selected variants: 2
> [1] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 5  | Genotype: 0  | Read Depth: 5  | WSAF: 0"  
> [2] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 25  | Genotype: 0  | Read Depth: 25  | WSAF: 0"
> [3] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 5  | Genotype: 0  | Read Depth: 5  | WSAF: 0"  
> [4] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 25  | Genotype: 0  | Read Depth: 25  | WSAF: 0"

# Test 3: Run on one variant on all samples (Appears to run as expected)

**Command:**
> test_var_id <- "PF3D7_0319700-p.Ile2221Phe"
> test_sample_id <-"KB-00-39" 
> coding_wsaf_table <- applyMethod(gdsobj,calc_AF_per_nucleotide,variant=all_variant_ids[which(gene_aa_change == test_var_id)])

**Output:**
> of selected variants: 2
> [281] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 5  | Genotype: 0  | Read Depth: 5  | WSAF: 0"  
> [638] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 25  | Genotype: 0  | Read Depth: 25  | WSAF: 0"
> [995] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 5  | Genotype: 0  | Read Depth: 5  | WSAF: 0"  
> [1238] "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 25  | Genotype: 0  | Read Depth: 25  | WSAF: 0"

I believe this may be a bug because "Sample: KB-00-39 at Variant: PF3D7_0319700-p.Ile2221Phe Alt count: 0  | Ref count: 0  | Genotype: 0  | Read Depth: 18  | WSAF: NaN " is not reported by either of the second two tests.

# Supplemental info:
My function which is being run on the gds object via applyMethod():

calc_AF_per_nucleotide <- function(node) {
  if (is.null(node)) {
    stop("No GDS node provided.")
  }
  
  ao <- seqGetData(node, "annotation/format/AO")
  ro <- seqGetData(node, "annotation/format/RO")
  gt <- seqGetData(node, "genotype")
  dp <- seqGetData(node, "annotation/format/DP")
  eachgene_aa_change <- seqGetData(node,"annotation/info/Gene_AA_Change")
  eachsample_id <- seqGetData(node, "sample.id")
  
  af <- ao / (ao + ro)
  print(paste("Sample:",eachsample_id,"at Variant:",eachgene_aa_change, "Alt count:", ao, " | Ref count:", ro, " | Genotype:", gt," | Read Depth:",dp, " | WSAF:", af))
  
  return(af)
}

Thank you,
George

**Comment by smgogarten** [comment]
`applyMethod` does work on multiple samples and variants, but it operates on them as a unit, not by iterating over each variant within the selected set. Also, when you read in the genotype or format nodes directly, you get a 3D array (sample x variant x allele).

The print statement in your function might be misleading. Here's an example similar to yours using an example data file: 

```
calc_AF_per_nucleotide <- function(node) {
    gt <- seqGetData(node, "genotype")
    dp <- seqGetData(node, "annotation/format/DP")
    eachgene_aa <- seqGetData(node,"annotation/info/AA")
    eachsample_id <- seqGetData(node, "sample.id")
    eachvariant_id <- seqGetData(node, "variant.id")
    
    print(paste("Sample:",eachsample_id))
    print(paste("Variant:",eachvariant_id))
    print(paste("AA:",eachgene_aa))
    print("genotype:")
    print(gt)
    print("read depth:")
    print(dp)
}

gds <- seqOpen(seqExampleFileName("gds"))
variant.id <- seqGetData(gds, "variant.id")
sample.id <- seqGetData(gds, "sample.id")
applyMethod(gds,calc_AF_per_nucleotide, variant.id[3:5], sample.id[1:2])

# of selected samples: 2
# of selected variants: 3
[1] "Sample: NA06984" "Sample: NA06985"
[1] "Variant: 3" "Variant: 4" "Variant: 5"
[1] "AA: A" "AA: C" "AA: G"
[1] "genotype:"
, , 1

      sample
allele [,1] [,2]
  [1,]    0    0
  [2,]    0    0

, , 2

      sample
allele [,1] [,2]
  [1,]    1    1
  [2,]    0    1

, , 3

      sample
allele [,1] [,2]
  [1,]    0    0
  [2,]    0    0

[1] "read depth:"
      variant
sample [,1] [,2] [,3]
  [1,]   12   15   70
  [2,]   17    4   24
      variant
sample [,1] [,2] [,3]
  [1,]   12   15   70
  [2,]   17    4   24
```
